#!/usr/bin/env bash
# install and configure HAproxy service

sudo apt-get update
sudo apt-get install -y haproxy
echo "
listen  hubservices
        bind *:80
        mode http
        option httpclose
        option forwardfor
        balance roundrobin
        server 174015-web-01 52.91.122.203:80 check
        server 174015-web-02 34.224.17.18:80 check
	" >> /etc/haproxy/haproxy.cfg
sudo echo "ENABLED=1" > /etc/default/haproxy
sudo service haproxy restart
