#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
# Displays minutes from 1 to 59

hour=0

while [ $count -le 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -le 59 ]
	do
		echo "$minute"
		(( minute++ ))
	done
	(( hour++ ))
done